create table if not exists public.lekhub_backoffice_reports (
  id uuid primary key default gen_random_uuid(),
  source_submission_id uuid not null unique references public.lekhub_submissions(id) on delete restrict,
  reference_code text not null,
  line_user_id text not null,
  member_name text not null,
  member_avatar text,
  item_count integer not null,
  total numeric(14,2) not null,
  imported_by_line_user_id text not null,
  imported_at timestamptz not null default now()
);

create table if not exists public.lekhub_backoffice_report_items (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.lekhub_backoffice_reports(id) on delete cascade,
  item_value text not null,
  category text not null,
  category_label text not null,
  heart numeric(14,2) not null,
  sort_order integer not null,
  created_at timestamptz not null default now()
);

alter table public.lekhub_backoffice_reports enable row level security;
alter table public.lekhub_backoffice_report_items enable row level security;

create index if not exists lekhub_backoffice_reports_imported_at_idx on public.lekhub_backoffice_reports(imported_at desc);
create index if not exists lekhub_backoffice_report_items_report_id_idx on public.lekhub_backoffice_report_items(report_id, sort_order);
