
begin;

create extension if not exists pgcrypto;

create table if not exists public.lekhub_tenants(
 tenant_key text primary key,
 display_name text not null,
 status text not null default 'active' check(status in ('active','locked','expired')),
 line_channel_id text,
 line_liff_id text,
 expires_at timestamptz,
 locked_at timestamptz,
 isolation_ready boolean not null default false,
 isolation_ready_at timestamptz,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 check(isolation_ready is not true or (
   nullif(trim(line_channel_id),'') is not null and
   nullif(trim(line_liff_id),'') is not null
 ))
);

create unique index if not exists lekhub_tenants_channel_uidx
 on public.lekhub_tenants(line_channel_id)
 where nullif(trim(line_channel_id),'') is not null;
create unique index if not exists lekhub_tenants_liff_uidx
 on public.lekhub_tenants(line_liff_id)
 where nullif(trim(line_liff_id),'') is not null;

create table if not exists public.lekhub_tenant_secrets(
 tenant_key text primary key references public.lekhub_tenants(tenant_key) on update cascade on delete cascade,
 line_channel_access_token text,
 updated_at timestamptz not null default now()
);

create table if not exists public.lekhub_settings(
 tenant_key text not null references public.lekhub_tenants(tenant_key) on update cascade on delete restrict,
 id boolean not null default true check(id=true),
 accepting boolean not null default true,
 close_time time not null default '23:59',
 timezone text not null default 'Asia/Bangkok',
 updated_at timestamptz not null default now(),
 category_amounts jsonb not null default '{}'::jsonb,
 cash_percent numeric not null default 0 check(cash_percent between 0 and 100),
 blocked_enabled boolean not null default true,
 round_date_override date,
 previous_round_number text,
 activity_prize_number text,
 activity_3front text,
 activity_3back text,
 activity_2bottom text,
 round_rollover_time time not null default '16:30',
 history_retention_days integer not null default 15 check(history_retention_days between 1 and 365),
 primary key(tenant_key,id)
);

create table if not exists public.lekhub_blocked_values(
 id bigint generated by default as identity primary key,
 tenant_key text not null references public.lekhub_tenants(tenant_key) on update cascade on delete restrict,
 item_value text not null check(item_value ~ '^[0-9]{1,6}$'),
 category text not null default '',
 active boolean not null default true,
 note text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(tenant_key,item_value,category)
);

create table if not exists public.lekhub_submissions(
 id uuid primary key default gen_random_uuid(),
 tenant_key text not null references public.lekhub_tenants(tenant_key) on update cascade on delete restrict,
 reference_code text not null,
 line_user_id text,
 member_name text not null default 'LINE Member',
 member_avatar text,
 status text not null default 'pending' check(status in ('pending','reviewed','cancelled')),
 item_count integer not null default 0 check(item_count>=0),
 total numeric not null default 0 check(total>=0),
 original_total numeric,
 is_cash boolean not null default false,
 cash_percent numeric not null default 0,
 attachment_url text,
 round_date date,
 created_at timestamptz not null default now(),
 reviewed_at timestamptz,
 reviewed_by text,
 admin_note text,
 unique(tenant_key,reference_code),
 unique(tenant_key,id)
);
create index if not exists lekhub_submissions_tenant_created_idx
 on public.lekhub_submissions(tenant_key,created_at desc);
create index if not exists lekhub_submissions_member_idx
 on public.lekhub_submissions(tenant_key,line_user_id,created_at desc);

create table if not exists public.lekhub_submission_items(
 id bigint generated by default as identity primary key,
 tenant_key text not null,
 submission_id uuid not null,
 item_value text not null,
 category text not null check(category in ('3topmix','3top','3front','3back','2top','single','mix','bottom')),
 category_label text not null,
 heart numeric not null check(heart>0),
 sort_order integer not null default 0,
 is_cash boolean not null default false,
 created_at timestamptz not null default now(),
 foreign key(tenant_key,submission_id)
  references public.lekhub_submissions(tenant_key,id) on update cascade on delete cascade,
 unique(tenant_key,id)
);
create index if not exists lekhub_submission_items_parent_idx
 on public.lekhub_submission_items(tenant_key,submission_id,sort_order);

create table if not exists public.lekhub_submission_events(
 id bigint generated by default as identity primary key,
 tenant_key text not null,
 submission_id uuid not null,
 event_type text not null check(event_type in ('created','status_changed','note_changed','member_cancelled')),
 old_status text,
 new_status text,
 admin_user_id text,
 note text,
 created_at timestamptz not null default now(),
 foreign key(tenant_key,submission_id)
  references public.lekhub_submissions(tenant_key,id) on update cascade on delete cascade
);

create table if not exists public.lekhub_backoffice_reports(
 id uuid primary key default gen_random_uuid(),
 tenant_key text not null references public.lekhub_tenants(tenant_key) on update cascade on delete restrict,
 source_submission_id uuid not null,
 reference_code text not null,
 line_user_id text not null,
 member_name text not null,
 member_avatar text,
 item_count integer not null,
 total numeric not null,
 original_total numeric,
 is_cash boolean not null default false,
 cash_percent numeric not null default 0,
 attachment_url text,
 round_date date,
 imported_by_line_user_id text not null,
 imported_at timestamptz not null default now(),
 unique(tenant_key,source_submission_id),
 unique(tenant_key,id),
 foreign key(tenant_key,source_submission_id)
  references public.lekhub_submissions(tenant_key,id) on update cascade on delete restrict
);
create index if not exists lekhub_backoffice_reports_tenant_idx
 on public.lekhub_backoffice_reports(tenant_key,imported_at desc);

create table if not exists public.lekhub_backoffice_report_items(
 id bigint generated by default as identity primary key,
 tenant_key text not null,
 report_id uuid not null,
 item_value text not null,
 category text not null,
 category_label text not null,
 heart numeric not null,
 sort_order integer not null,
 is_cash boolean not null default false,
 created_at timestamptz not null default now(),
 foreign key(tenant_key,report_id)
  references public.lekhub_backoffice_reports(tenant_key,id) on update cascade on delete cascade
);

create table if not exists public.lekhub_activity_rewards(
 id bigint generated by default as identity primary key,
 tenant_key text not null references public.lekhub_tenants(tenant_key) on update cascade on delete restrict,
 round_date date not null,
 prize_number text not null,
 submission_id uuid not null,
 item_id bigint not null,
 line_user_id text not null,
 member_name text not null,
 selected_value text not null,
 category text not null,
 category_label text not null,
 stake numeric not null,
 multiplier numeric not null,
 reward_amount numeric not null,
 created_at timestamptz not null default now(),
 foreign key(tenant_key,submission_id)
  references public.lekhub_submissions(tenant_key,id) on update cascade on delete cascade,
 foreign key(tenant_key,item_id)
  references public.lekhub_submission_items(tenant_key,id) on update cascade on delete cascade,
 unique(tenant_key,round_date,item_id)
);
create index if not exists lekhub_rewards_member_idx
 on public.lekhub_activity_rewards(tenant_key,line_user_id,round_date desc);

create table if not exists public.lekhub_member_notes(
 tenant_key text not null references public.lekhub_tenants(tenant_key) on update cascade on delete restrict,
 line_user_id text not null,
 note text not null default '',
 updated_at timestamptz not null default now(),
 primary key(tenant_key,line_user_id)
);

create table if not exists public.lekhub_line_admins(
 tenant_key text not null references public.lekhub_tenants(tenant_key) on update cascade on delete restrict,
 line_user_id text not null,
 display_name text not null,
 picture_url text,
 role text not null default 'admin' check(role in ('owner','super_admin','admin')),
 is_active boolean not null default true,
 created_at timestamptz not null default now(),
 primary key(tenant_key,line_user_id)
);

create table if not exists public.lekhub_line_admin_sessions(
 token_hash text primary key,
 tenant_key text not null,
 line_user_id text not null,
 expires_at timestamptz not null,
 created_at timestamptz not null default now(),
 foreign key(tenant_key,line_user_id)
  references public.lekhub_line_admins(tenant_key,line_user_id) on update cascade on delete cascade
);

create table if not exists public.lekhub_line_admin_requests(
 tenant_key text not null references public.lekhub_tenants(tenant_key) on update cascade on delete cascade,
 line_user_id text not null,
 display_name text not null,
 picture_url text,
 requested_at timestamptz not null default now(),
 primary key(tenant_key,line_user_id)
);

-- Dedicated platform tenant for the system owner. It never receives member submissions.
insert into public.lekhub_tenants(tenant_key,display_name,status,isolation_ready)
values('platform','LekHub Platform','active',false)
on conflict(tenant_key) do nothing;

create or replace function public.lekhub_digits_key(p_value text)
returns text language sql immutable strict
as $$
 select string_agg(ch,'' order by ch)
 from regexp_split_to_table(p_value,'') ch where ch<>'';
$$;

create or replace function public.lekhub_tenant_from_channel(
 p_channel_id text,p_require_ready boolean default true
) returns text language plpgsql security definer set search_path='public'
as $$
declare v public.lekhub_tenants%rowtype;
begin
 select * into v from public.lekhub_tenants
 where line_channel_id=nullif(trim(p_channel_id),'') limit 1;
 if not found then raise exception 'tenant_channel_not_found'; end if;
 if v.status<>'active' then raise exception 'tenant_inactive'; end if;
 if v.expires_at is not null and v.expires_at<=now() then raise exception 'tenant_expired'; end if;
 if p_require_ready and v.isolation_ready is not true then raise exception 'tenant_not_ready'; end if;
 return v.tenant_key;
end $$;

create or replace function public.lekhub_effective_round_date_for_tenant(
 p_tenant text,p_at timestamptz default now()
) returns date language plpgsql stable security definer set search_path='public'
as $$
declare v_override date;v_tz text:='Asia/Bangkok';v_cut time:='16:30';v_local timestamp;v_day date;v_time time;
begin
 if nullif(trim(p_tenant),'') is null then raise exception 'tenant_required'; end if;
 select round_date_override,coalesce(timezone,'Asia/Bangkok'),coalesce(round_rollover_time,'16:30')
 into v_override,v_tz,v_cut from public.lekhub_settings where tenant_key=p_tenant and id=true;
 if v_override is not null then return v_override; end if;
 v_local:=p_at at time zone v_tz;v_day:=v_local::date;v_time:=v_local::time;
 if extract(day from v_day)::int=1 then
  if v_time<v_cut then return v_day; else return v_day+15; end if;
 elsif extract(day from v_day)::int between 2 and 15 then
  return date_trunc('month',v_day)::date+15;
 elsif extract(day from v_day)::int=16 then
  if v_time<v_cut then return v_day; else return (date_trunc('month',v_day)+interval '1 month')::date; end if;
 else
  return (date_trunc('month',v_day)+interval '1 month')::date;
 end if;
end $$;

create or replace function public.get_lekhub_public_status_v2(p_channel_id text)
returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_tenant text;v public.lekhub_settings%rowtype;v_blocked jsonb;v_round date;
begin
 v_tenant:=public.lekhub_tenant_from_channel(p_channel_id,true);
 select * into v from public.lekhub_settings where tenant_key=v_tenant and id=true;
 if not found then raise exception 'tenant_settings_missing'; end if;
 select coalesce(jsonb_agg(item_value order by item_value),'[]'::jsonb)
 into v_blocked from public.lekhub_blocked_values
 where tenant_key=v_tenant and active=true;
 v_round:=public.lekhub_effective_round_date_for_tenant(v_tenant,now());
 return jsonb_build_object(
  'success',true,'tenant_key',v_tenant,
  'is_open',v.accepting and ((now() at time zone v.timezone)::time<v.close_time),
  'close_time',v.close_time,'cash_percent',v.cash_percent,
  'blocked_enabled',v.blocked_enabled,
  'blocked_values',case when v.blocked_enabled then v_blocked else '[]'::jsonb end,
  'round_date',v_round,'previous_round_number',v.previous_round_number
 );
end $$;

create or replace function public.lekhub_log_submission_created()
returns trigger language plpgsql set search_path='public'
as $$
begin
 insert into public.lekhub_submission_events(tenant_key,submission_id,event_type,new_status,note)
 values(new.tenant_key,new.id,'created',new.status,'member_submission');
 return new;
end $$;
drop trigger if exists lekhub_submission_created_trg on public.lekhub_submissions;
create trigger lekhub_submission_created_trg
after insert on public.lekhub_submissions
for each row execute function public.lekhub_log_submission_created();

create or replace function public.submit_lekhub_submission_v2(
 p_channel_id text,p_reference_code text,p_line_user_id text,p_member_name text,
 p_member_avatar text,p_items jsonb,p_attachment_url text default null
) returns jsonb language plpgsql security definer set search_path='public'
as $$
declare
 v_tenant text;v_submission_id uuid;v_count int;v_original_total numeric(14,2):=0;
 v_total numeric(14,2);v_item jsonb;v_order int:=0;v_value text;v_category text;
 v_label text;v_heart numeric;v_cash boolean:=false;v_item_cash boolean;
 v_settings public.lekhub_settings%rowtype;v_recent int;v_cash_percent numeric(5,2);v_round date;
begin
 v_tenant:=public.lekhub_tenant_from_channel(p_channel_id,true);
 if coalesce(trim(p_reference_code),'')='' or length(p_reference_code)>64 then raise exception 'invalid_reference'; end if;
 if coalesce(trim(p_line_user_id),'')='' then raise exception 'line_user_required'; end if;
 select * into v_settings from public.lekhub_settings where tenant_key=v_tenant and id=true;
 if not found then raise exception 'tenant_settings_missing'; end if;
 if not v_settings.accepting then raise exception 'not_accepting'; end if;
 if (now() at time zone v_settings.timezone)::time>=v_settings.close_time then raise exception 'outside_accepting_time'; end if;
 select count(*) into v_recent from public.lekhub_submissions
  where tenant_key=v_tenant and line_user_id=p_line_user_id and created_at>=now()-interval '60 seconds';
 if v_recent>=10 then raise exception 'rate_limited'; end if;
 if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'items_required'; end if;
 if jsonb_array_length(p_items)>100 then raise exception 'too_many_items'; end if;
 v_count:=jsonb_array_length(p_items);
 for v_item in select * from jsonb_array_elements(p_items) loop
  v_value:=regexp_replace(coalesce(v_item->>'value',''),'[^0-9]','','g');
  v_category:=left(coalesce(v_item->>'category',''),32);
  if v_category not in ('3topmix','3top','3front','3back','2top','single','mix','bottom') then raise exception 'invalid_category'; end if;
  v_label:=left(coalesce(v_item->>'category_label',v_category),80);
  begin v_heart:=(v_item->>'heart')::numeric; exception when others then raise exception 'invalid_heart'; end;
  if v_value='' or length(v_value)>6 then raise exception 'invalid_item_value'; end if;
  if v_heart<=0 or v_heart>100000000 then raise exception 'invalid_heart'; end if;
  if v_settings.blocked_enabled and exists(
   select 1 from public.lekhub_blocked_values b
   where b.tenant_key=v_tenant and b.active and b.item_value=v_value
     and (b.category='' or b.category=v_category)
  ) then raise exception 'blocked_value'; end if;
  v_original_total:=v_original_total+v_heart;
  v_item_cash:=coalesce((v_item->>'cash')::boolean,false);
  if v_item_cash then v_cash:=true; end if;
 end loop;
 v_cash_percent:=case when v_cash then greatest(0,least(100,v_settings.cash_percent)) else 0 end;
 v_total:=round(v_original_total*(1-v_cash_percent/100.0),2);
 v_round:=public.lekhub_effective_round_date_for_tenant(v_tenant,now());
 insert into public.lekhub_submissions(
  tenant_key,reference_code,line_user_id,member_name,member_avatar,item_count,total,
  original_total,is_cash,cash_percent,attachment_url,round_date
 ) values(
  v_tenant,left(trim(p_reference_code),64),left(trim(p_line_user_id),128),
  left(coalesce(nullif(trim(p_member_name),''),'LINE Member'),120),
  left(nullif(trim(p_member_avatar),''),500),v_count,v_total,v_original_total,
  v_cash,v_cash_percent,left(nullif(trim(p_attachment_url),''),1000),v_round
 ) returning id into v_submission_id;
 for v_item in select * from jsonb_array_elements(p_items) loop
  v_order:=v_order+1;
  v_value:=regexp_replace(coalesce(v_item->>'value',''),'[^0-9]','','g');
  v_category:=left(coalesce(v_item->>'category',''),32);
  v_label:=left(coalesce(v_item->>'category_label',v_category),80);
  v_heart:=(v_item->>'heart')::numeric;
  v_item_cash:=coalesce((v_item->>'cash')::boolean,false);
  insert into public.lekhub_submission_items(
   tenant_key,submission_id,item_value,category,category_label,heart,sort_order,is_cash
  ) values(v_tenant,v_submission_id,v_value,v_category,v_label,v_heart,v_order,v_item_cash);
 end loop;
 return jsonb_build_object(
  'success',true,'tenant_key',v_tenant,'id',v_submission_id,
  'reference_code',p_reference_code,'item_count',v_count,'original_total',v_original_total,
  'total',v_total,'cash_percent',v_cash_percent,'is_cash',v_cash,'round_date',v_round,'status','pending'
 );
exception when unique_violation then
 return jsonb_build_object('success',false,'reason','duplicate_reference');
end $$;

create or replace function public.lekhub_check_line_admin_session(p_token text)
returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_row record;
begin
 if nullif(trim(p_token),'') is null then return jsonb_build_object('ok',false); end if;
 select a.line_user_id,a.display_name,a.role,a.tenant_key into v_row
 from public.lekhub_line_admin_sessions s
 join public.lekhub_line_admins a on a.tenant_key=s.tenant_key and a.line_user_id=s.line_user_id
 join public.lekhub_tenants t on t.tenant_key=s.tenant_key
 where s.token_hash=encode(digest(p_token,'sha256'),'hex')
   and s.expires_at>now() and a.is_active
   and t.status='active' and (t.expires_at is null or t.expires_at>now())
 limit 1;
 if not found then return jsonb_build_object('ok',false); end if;
 return jsonb_build_object(
  'ok',true,'user_id',v_row.line_user_id,'display_name',v_row.display_name,
  'role',v_row.role,'tenant_key',v_row.tenant_key
 );
end $$;

create or replace function public.lekhub_logout_line_admin_session(p_token text)
returns boolean language plpgsql security definer set search_path='public'
as $$
begin
 delete from public.lekhub_line_admin_sessions
 where token_hash=encode(digest(coalesce(p_token,''),'sha256'),'hex');
 return true;
end $$;

create or replace function public.lekhub_line_admin_login_v2(
 p_channel_id text,p_line_user_id text,p_display_name text,p_picture_url text default null
) returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_tenant text;v_role text;v_active boolean;v_token text;
begin
 v_tenant:=public.lekhub_tenant_from_channel(p_channel_id,true);
 if nullif(trim(p_line_user_id),'') is null or nullif(trim(p_display_name),'') is null then
  return jsonb_build_object('ok',false,'error','invalid_line_profile');
 end if;
 select role,is_active into v_role,v_active from public.lekhub_line_admins
 where tenant_key=v_tenant and line_user_id=p_line_user_id;
 if not found then
  insert into public.lekhub_line_admin_requests(tenant_key,line_user_id,display_name,picture_url,requested_at)
  values(v_tenant,p_line_user_id,p_display_name,p_picture_url,now())
  on conflict(tenant_key,line_user_id) do update
   set display_name=excluded.display_name,picture_url=excluded.picture_url,requested_at=now();
  return jsonb_build_object('ok',false,'error','line_user_not_admin');
 end if;
 if not coalesce(v_active,false) then return jsonb_build_object('ok',false,'error','line_user_not_admin'); end if;
 update public.lekhub_line_admins
 set display_name=p_display_name,picture_url=coalesce(p_picture_url,picture_url)
 where tenant_key=v_tenant and line_user_id=p_line_user_id;
 delete from public.lekhub_line_admin_sessions where expires_at<=now();
 v_token:=encode(gen_random_bytes(32),'hex');
 insert into public.lekhub_line_admin_sessions(token_hash,tenant_key,line_user_id,expires_at)
 values(encode(digest(v_token,'sha256'),'hex'),v_tenant,p_line_user_id,now()+interval '12 hours');
 return jsonb_build_object('ok',true,'session_token',v_token,'display_name',p_display_name,'role',v_role,'tenant_key',v_tenant);
end $$;

create or replace function public.lekhub_line_admin_get_settings(p_token text)
returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_tenant text;v public.lekhub_settings%rowtype;v_blocked jsonb;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true then raise exception 'admin_required'; end if;
 v_tenant:=nullif(v_session->>'tenant_key','');
 if v_tenant is null then raise exception 'tenant_required'; end if;
 select * into v from public.lekhub_settings where tenant_key=v_tenant and id=true;
 select coalesce(jsonb_agg(item_value order by item_value),'[]'::jsonb) into v_blocked
 from public.lekhub_blocked_values where tenant_key=v_tenant and active=true;
 return jsonb_build_object(
  'success',true,'accepting',coalesce(v.accepting,true),'close_time',coalesce(v.close_time,'23:59'),
  'timezone',coalesce(v.timezone,'Asia/Bangkok'),'category_amounts',coalesce(v.category_amounts,'{}'),
  'cash_percent',coalesce(v.cash_percent,0),'blocked_enabled',coalesce(v.blocked_enabled,true),
  'blocked_values',v_blocked,'round_date_override',v.round_date_override,
  'previous_round_number',v.previous_round_number,'activity_prize_number',v.activity_prize_number,
  'activity_3front',v.activity_3front,'activity_3back',v.activity_3back,'activity_2bottom',v.activity_2bottom
 );
end $$;

create or replace function public.lekhub_line_admin_replace_blocked_values(p_token text,p_values text[])
returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_tenant text;v text;v_clean text;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true then raise exception 'admin_required'; end if;
 v_tenant:=nullif(v_session->>'tenant_key','');
 if v_tenant is null then raise exception 'tenant_required'; end if;
 update public.lekhub_blocked_values set active=false,updated_at=now()
 where tenant_key=v_tenant and active=true;
 foreach v in array coalesce(p_values,array[]::text[]) loop
  v_clean:=regexp_replace(coalesce(v,''),'[^0-9]','','g');
  if v_clean<>'' then
   insert into public.lekhub_blocked_values(tenant_key,item_value,category,active,note,updated_at)
   values(v_tenant,v_clean,'',true,'ตั้งค่าจากหลังบ้าน',now())
   on conflict(tenant_key,item_value,category) do update
   set active=true,note=excluded.note,updated_at=now();
  end if;
 end loop;
 return jsonb_build_object('success',true);
end $$;

create or replace function public.lekhub_line_admin_update_category_amounts(
 p_token text,p_category_amounts jsonb
) returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_tenant text;v jsonb;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true then raise exception 'admin_required'; end if;
 v_tenant:=nullif(v_session->>'tenant_key','');if v_tenant is null then raise exception 'tenant_required';end if;
 v:=coalesce(p_category_amounts,'{}');
 update public.lekhub_settings set category_amounts=v,updated_at=now()
 where tenant_key=v_tenant and id=true;
 return jsonb_build_object('success',true,'category_amounts',v);
end $$;

create or replace function public.lekhub_line_admin_update_settings(
 p_token text,p_accepting boolean,p_close_time time,p_category_amounts jsonb default '{}',
 p_cash_percent numeric default 0,p_blocked_enabled boolean default true,
 p_round_date date default null,p_previous_round_number text default null
) returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_tenant text;v_prev text;v public.lekhub_settings%rowtype;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true then raise exception 'admin_required'; end if;
 v_tenant:=nullif(v_session->>'tenant_key','');if v_tenant is null then raise exception 'tenant_required';end if;
 if coalesce(p_cash_percent,0)<0 or coalesce(p_cash_percent,0)>100 then raise exception 'invalid_cash_percent';end if;
 v_prev:=nullif(regexp_replace(coalesce(p_previous_round_number,''),'[^0-9]','','g'),'');
 if v_prev is not null and length(v_prev)<>6 then raise exception 'previous_round_number_must_be_6_digits';end if;
 update public.lekhub_settings set
  accepting=coalesce(p_accepting,true),close_time=coalesce(p_close_time,'23:59'),
  category_amounts=coalesce(p_category_amounts,'{}'),cash_percent=coalesce(p_cash_percent,0),
  blocked_enabled=coalesce(p_blocked_enabled,true),round_date_override=p_round_date,
  previous_round_number=v_prev,updated_at=now()
 where tenant_key=v_tenant and id=true returning * into v;
 if not found then raise exception 'tenant_settings_missing';end if;
 return jsonb_build_object(
  'success',true,'accepting',v.accepting,'close_time',v.close_time,
  'category_amounts',v.category_amounts,'cash_percent',v.cash_percent,
  'blocked_enabled',v.blocked_enabled,'round_date_override',v.round_date_override,
  'previous_round_number',v.previous_round_number
 );
end $$;

create or replace function public.lekhub_line_admin_set_submission_status(
 p_token text,p_submission_id uuid,p_status text
) returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_tenant text;v_row public.lekhub_submissions%rowtype;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true then raise exception 'admin_required';end if;
 v_tenant:=nullif(v_session->>'tenant_key','');if v_tenant is null then raise exception 'tenant_required';end if;
 if p_status not in ('pending','reviewed','cancelled') then raise exception 'invalid_status';end if;
 update public.lekhub_submissions set
  status=p_status,reviewed_at=case when p_status='reviewed' then now() else null end
 where tenant_key=v_tenant and id=p_submission_id returning * into v_row;
 if not found then raise exception 'submission_not_found';end if;
 return jsonb_build_object('success',true,'id',v_row.id,'status',v_row.status,'reviewed_at',v_row.reviewed_at);
end $$;

create or replace function public.lekhub_line_admin_list_oa_inbox(
 p_token text,p_status text default null,p_limit integer default 100
) returns table(
 id uuid,reference_code text,line_user_id text,member_name text,member_avatar text,status text,
 item_count integer,total numeric,created_at timestamptz,reviewed_at timestamptz,imported_at timestamptz,
 attachment_url text,round_date date,items jsonb
) language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_tenant text;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true then raise exception 'admin_required';end if;
 v_tenant:=nullif(v_session->>'tenant_key','');if v_tenant is null then raise exception 'tenant_required';end if;
 return query
 select s.id,s.reference_code,s.line_user_id,s.member_name,s.member_avatar,s.status,
 s.item_count,s.total,s.created_at,s.reviewed_at,r.imported_at,s.attachment_url,s.round_date,
 coalesce((
  select jsonb_agg(jsonb_build_object(
   'id',i.id,'value',i.item_value,'category',i.category,'category_label',i.category_label,
   'heart',i.heart,'cash',i.is_cash,'sort_order',i.sort_order
  ) order by i.sort_order)
  from public.lekhub_submission_items i
  where i.tenant_key=v_tenant and i.submission_id=s.id
 ),'[]'::jsonb)
 from public.lekhub_submissions s
 left join public.lekhub_backoffice_reports r
  on r.tenant_key=v_tenant and r.source_submission_id=s.id
 where s.tenant_key=v_tenant and (p_status is null or s.status=p_status)
 order by s.created_at desc limit greatest(1,least(coalesce(p_limit,100),500));
end $$;

create or replace function public.lekhub_line_admin_import_submission(
 p_token text,p_submission_id uuid
) returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_tenant text;v_admin text;v_submission public.lekhub_submissions%rowtype;v_report uuid;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true then raise exception 'admin_required';end if;
 v_tenant:=nullif(v_session->>'tenant_key','');if v_tenant is null then raise exception 'tenant_required';end if;
 v_admin:=v_session->>'user_id';
 select * into v_submission from public.lekhub_submissions
 where tenant_key=v_tenant and id=p_submission_id;
 if not found then raise exception 'submission_not_found';end if;
 if v_submission.status<>'reviewed' then return jsonb_build_object('success',false,'reason','review_required');end if;
 select id into v_report from public.lekhub_backoffice_reports
 where tenant_key=v_tenant and source_submission_id=p_submission_id;
 if found then return jsonb_build_object('success',true,'already_imported',true,'report_id',v_report);end if;
 insert into public.lekhub_backoffice_reports(
  tenant_key,source_submission_id,reference_code,line_user_id,member_name,member_avatar,
  item_count,total,original_total,is_cash,cash_percent,attachment_url,round_date,imported_by_line_user_id
 ) values(
  v_tenant,v_submission.id,v_submission.reference_code,coalesce(v_submission.line_user_id,''),
  v_submission.member_name,v_submission.member_avatar,v_submission.item_count,v_submission.total,
  coalesce(v_submission.original_total,v_submission.total),v_submission.is_cash,v_submission.cash_percent,
  v_submission.attachment_url,v_submission.round_date,v_admin
 ) returning id into v_report;
 insert into public.lekhub_backoffice_report_items(
  tenant_key,report_id,item_value,category,category_label,heart,sort_order,is_cash
 )
 select v_tenant,v_report,item_value,category,category_label,heart,sort_order,is_cash
 from public.lekhub_submission_items where tenant_key=v_tenant and submission_id=p_submission_id;
 return jsonb_build_object('success',true,'already_imported',false,'report_id',v_report);
end $$;

create or replace function public.lekhub_line_admin_list_backoffice_reports(
 p_token text,p_limit integer default 200
) returns table(
 id uuid,source_submission_id uuid,reference_code text,line_user_id text,member_name text,
 member_avatar text,item_count integer,total numeric,imported_by_line_user_id text,imported_at timestamptz,
 submitted_at timestamptz,attachment_url text,round_date date,items jsonb
) language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_tenant text;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true then raise exception 'admin_required';end if;
 v_tenant:=nullif(v_session->>'tenant_key','');if v_tenant is null then raise exception 'tenant_required';end if;
 return query
 select r.id,r.source_submission_id,r.reference_code,r.line_user_id,r.member_name,r.member_avatar,
 r.item_count,r.total,r.imported_by_line_user_id,r.imported_at,s.created_at,r.attachment_url,r.round_date,
 coalesce((
  select jsonb_agg(jsonb_build_object(
   'id',i.id,'value',i.item_value,'category',i.category,'category_label',i.category_label,
   'heart',i.heart,'cash',i.is_cash,'sort_order',i.sort_order
  ) order by i.sort_order)
  from public.lekhub_backoffice_report_items i
  where i.tenant_key=v_tenant and i.report_id=r.id
 ),'[]'::jsonb)
 from public.lekhub_backoffice_reports r
 join public.lekhub_submissions s on s.tenant_key=v_tenant and s.id=r.source_submission_id
 where r.tenant_key=v_tenant
 order by r.imported_at desc limit greatest(1,least(coalesce(p_limit,200),500));
end $$;

create or replace function public.lekhub_line_admin_list_members(
 p_token text,p_limit integer default 500
) returns table(
 line_user_id text,member_name text,total_played numeric,total_rewards numeric,last_activity timestamptz,note text
) language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_tenant text;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true then raise exception 'admin_required';end if;
 v_tenant:=nullif(v_session->>'tenant_key','');if v_tenant is null then raise exception 'tenant_required';end if;
 return query
 select s.line_user_id,(array_agg(s.member_name order by s.created_at desc))[1],
 coalesce(sum(coalesce(s.original_total,s.total)),0),
 coalesce((select sum(r.reward_amount) from public.lekhub_activity_rewards r
  where r.tenant_key=v_tenant and r.line_user_id=s.line_user_id),0),
 max(s.created_at),
 coalesce((select n.note from public.lekhub_member_notes n
  where n.tenant_key=v_tenant and n.line_user_id=s.line_user_id),'')
 from public.lekhub_submissions s
 where s.tenant_key=v_tenant and s.line_user_id is not null
 group by s.line_user_id order by max(s.created_at) desc
 limit greatest(1,least(coalesce(p_limit,500),1000));
end $$;

create or replace function public.lekhub_member_get_note_v2(p_channel_id text,p_line_user_id text)
returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_tenant text;
begin
 v_tenant:=public.lekhub_tenant_from_channel(p_channel_id,true);
 return jsonb_build_object('success',true,'note',coalesce((
  select note from public.lekhub_member_notes
  where tenant_key=v_tenant and line_user_id=p_line_user_id
 ),''));
end $$;

create or replace function public.lekhub_member_set_note_v2(
 p_channel_id text,p_line_user_id text,p_note text
) returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_tenant text;
begin
 v_tenant:=public.lekhub_tenant_from_channel(p_channel_id,true);
 if coalesce(trim(p_line_user_id),'')='' then raise exception 'line_user_required';end if;
 if length(coalesce(p_note,''))>5000 then raise exception 'note_too_long';end if;
 insert into public.lekhub_member_notes(tenant_key,line_user_id,note,updated_at)
 values(v_tenant,left(trim(p_line_user_id),128),coalesce(p_note,''),now())
 on conflict(tenant_key,line_user_id) do update set note=excluded.note,updated_at=now();
 return jsonb_build_object('success',true,'note',coalesce(p_note,''));
end $$;

create or replace function public.lekhub_member_list_submissions_v2(
 p_channel_id text,p_line_user_id text,p_limit integer default 100
) returns table(
 id uuid,reference_code text,status text,item_count integer,total numeric,created_at timestamptz,
 attachment_url text,round_date date,reward_total numeric,rewards jsonb,items jsonb
) language plpgsql security definer set search_path='public'
as $$
declare v_tenant text;
begin
 v_tenant:=public.lekhub_tenant_from_channel(p_channel_id,true);
 return query
 select s.id,s.reference_code,s.status,s.item_count,s.total,s.created_at,s.attachment_url,s.round_date,
 coalesce((select sum(r.reward_amount) from public.lekhub_activity_rewards r
  where r.tenant_key=v_tenant and r.submission_id=s.id),0),
 coalesce((select jsonb_agg(jsonb_build_object(
  'selected_value',r.selected_value,'category_label',r.category_label,'stake',r.stake,
  'multiplier',r.multiplier,'reward_amount',r.reward_amount,'prize_number',r.prize_number
 ) order by r.id) from public.lekhub_activity_rewards r
  where r.tenant_key=v_tenant and r.submission_id=s.id),'[]'::jsonb),
 coalesce((select jsonb_agg(jsonb_build_object(
  'id',i.id,'value',i.item_value,'category_label',i.category_label,'heart',i.heart,
  'cash',i.is_cash,'sort_order',i.sort_order
 ) order by i.sort_order) from public.lekhub_submission_items i
  where i.tenant_key=v_tenant and i.submission_id=s.id),'[]'::jsonb)
 from public.lekhub_submissions s
 where s.tenant_key=v_tenant and s.line_user_id=p_line_user_id
   and s.created_at>=now()-interval '15 days'
 order by s.created_at desc limit greatest(1,least(coalesce(p_limit,100),300));
end $$;

create or replace function public.lekhub_line_admin_set_activity_result(
 p_token text,p_prize_number text,p_3front text,p_3back text,p_2bottom text
) returns jsonb language plpgsql security definer set search_path='public'
as $$
declare
 v_session jsonb;v_tenant text;v_prize text;v_front text;v_back text;v_bottom text;
 v_round date;v_rates jsonb;v_count int;v_total numeric;v_winners jsonb;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true then raise exception 'admin_required';end if;
 v_tenant:=nullif(v_session->>'tenant_key','');if v_tenant is null then raise exception 'tenant_required';end if;
 v_prize:=regexp_replace(coalesce(p_prize_number,''),'[^0-9]','','g');
 v_front:=regexp_replace(coalesce(p_3front,''),'[^0-9]','','g');
 v_back:=regexp_replace(coalesce(p_3back,''),'[^0-9]','','g');
 v_bottom:=regexp_replace(coalesce(p_2bottom,''),'[^0-9]','','g');
 if length(v_prize)<>6 then raise exception 'activity_prize_number_must_be_6_digits';end if;
 if v_front<>'' and length(v_front)<>3 then raise exception 'activity_3front_must_be_3_digits';end if;
 if v_back<>'' and length(v_back)<>3 then raise exception 'activity_3back_must_be_3_digits';end if;
 if v_bottom<>'' and length(v_bottom)<>2 then raise exception 'activity_2bottom_must_be_2_digits';end if;
 select public.lekhub_effective_round_date_for_tenant(v_tenant,now()),category_amounts
 into v_round,v_rates from public.lekhub_settings where tenant_key=v_tenant and id=true;
 update public.lekhub_settings set
  activity_prize_number=v_prize,activity_3front=nullif(v_front,''),
  activity_3back=nullif(v_back,''),activity_2bottom=nullif(v_bottom,''),updated_at=now()
 where tenant_key=v_tenant and id=true;
 delete from public.lekhub_activity_rewards where tenant_key=v_tenant and round_date=v_round;
 insert into public.lekhub_activity_rewards(
  tenant_key,round_date,prize_number,submission_id,item_id,line_user_id,member_name,
  selected_value,category,category_label,stake,multiplier,reward_amount
 )
 select v_tenant,s.round_date,v_prize,s.id,i.id,s.line_user_id,s.member_name,
 i.item_value,i.category,i.category_label,i.heart,
 coalesce(nullif(v_rates->>i.category,'')::numeric,0),
 round((i.heart/10.0)*coalesce(nullif(v_rates->>i.category,'')::numeric,0),2)
 from public.lekhub_submissions s
 join public.lekhub_submission_items i
  on i.tenant_key=v_tenant and i.submission_id=s.id
 where s.tenant_key=v_tenant and s.round_date=v_round
 and coalesce(nullif(v_rates->>i.category,'')::numeric,0)>0
 and (
  (i.category='3top' and i.item_value=right(v_prize,3)) or
  (i.category in ('3topmix','mix') and length(i.item_value)=3 and public.lekhub_digits_key(i.item_value)=public.lekhub_digits_key(right(v_prize,3))) or
  (i.category='3front' and v_front<>'' and i.item_value=v_front) or
  (i.category='3back' and v_back<>'' and i.item_value=v_back) or
  (i.category='2top' and i.item_value=right(v_prize,2)) or
  (i.category='bottom' and v_bottom<>'' and i.item_value=v_bottom) or
  (i.category='single' and i.item_value=right(v_prize,1))
 );
 select count(*),coalesce(sum(reward_amount),0) into v_count,v_total
 from public.lekhub_activity_rewards where tenant_key=v_tenant and round_date=v_round;
 select coalesce(jsonb_agg(jsonb_build_object(
  'line_user_id',x.line_user_id,'member_name',x.member_name,'reward_total',x.reward_total,
  'winning_items',x.winning_items
 ) order by x.member_name),'[]'::jsonb) into v_winners
 from (
  select r.line_user_id,max(r.member_name) member_name,sum(r.reward_amount) reward_total,
  jsonb_agg(jsonb_build_object(
   'selected_value',r.selected_value,'category',r.category,'category_label',r.category_label,
   'stake',r.stake,'multiplier',r.multiplier,'reward_amount',r.reward_amount
  ) order by r.category_label,r.selected_value) winning_items
  from public.lekhub_activity_rewards r
  where r.tenant_key=v_tenant and r.round_date=v_round group by r.line_user_id
 ) x;
 return jsonb_build_object(
  'success',true,'round_date',v_round,'prize_number',v_prize,
  '3front',nullif(v_front,''),'3back',nullif(v_back,''),'2bottom',nullif(v_bottom,''),
  'winner_items',v_count,'reward_total',v_total,'winners',v_winners
 );
end $$;

create or replace function public.lekhub_public_tenant_liff(p_tenant_key text)
returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v public.lekhub_tenants%rowtype;
begin
 select * into v from public.lekhub_tenants where tenant_key=lower(trim(p_tenant_key));
 if not found then return jsonb_build_object('ok',false,'error','tenant_not_found');end if;
 if v.status<>'active' or (v.expires_at is not null and v.expires_at<=now()) then
  return jsonb_build_object('ok',false,'error','tenant_inactive');
 end if;
 if not v.isolation_ready or nullif(trim(v.line_liff_id),'') is null or nullif(trim(v.line_channel_id),'') is null then
  return jsonb_build_object('ok',false,'error','tenant_not_ready');
 end if;
 return jsonb_build_object('ok',true,'tenant_key',v.tenant_key,'liff_id',v.line_liff_id);
end $$;

create or replace function public.lekhub_owner_create_tenant_v3(
 p_token text,p_tenant_key text,p_display_name text,p_line_channel_id text default null,
 p_line_liff_id text default null,p_line_channel_access_token text default null,p_expires_at timestamptz default null
) returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_key text;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true or
    coalesce(v_session->>'role','') not in ('owner','super_admin') then
  raise exception 'owner_required';
 end if;
 v_key:=lower(trim(coalesce(p_tenant_key,'')));
 if v_key='' or v_key !~ '^[a-z0-9][a-z0-9-]{0,47}$' then raise exception 'invalid_tenant_key';end if;
 if trim(coalesce(p_display_name,''))='' then raise exception 'display_name_required';end if;
 insert into public.lekhub_tenants(
  tenant_key,display_name,status,line_channel_id,line_liff_id,expires_at,isolation_ready,updated_at
 ) values(
  v_key,left(trim(p_display_name),120),'active',nullif(trim(p_line_channel_id),''),
  nullif(trim(p_line_liff_id),''),p_expires_at,false,now()
 );
 insert into public.lekhub_settings(tenant_key,id,accepting,close_time,timezone,updated_at)
 values(v_key,true,true,'23:59','Asia/Bangkok',now());
 if nullif(trim(p_line_channel_access_token),'') is not null then
  insert into public.lekhub_tenant_secrets(tenant_key,line_channel_access_token)
  values(v_key,trim(p_line_channel_access_token));
 end if;
 return jsonb_build_object('ok',true,'row',(
  select to_jsonb(t) from public.lekhub_tenants t where t.tenant_key=v_key
 ));
exception when unique_violation then raise exception 'tenant_or_line_config_already_exists';
end $$;

create or replace function public.lekhub_owner_list_tenants(p_token text)
returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_rows jsonb;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true or
    coalesce(v_session->>'role','') not in ('owner','super_admin') then raise exception 'owner_required';end if;
 select coalesce(jsonb_agg(to_jsonb(t) order by t.created_at desc),'[]')
 into v_rows from public.lekhub_tenants t where t.tenant_key<>'platform';
 return jsonb_build_object('ok',true,'rows',v_rows);
end $$;

create or replace function public.lekhub_owner_list_admin_requests(p_token text)
returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_rows jsonb;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true or
    coalesce(v_session->>'role','') not in ('owner','super_admin') then raise exception 'owner_required';end if;
 select coalesce(jsonb_agg(jsonb_build_object(
  'tenant_key',r.tenant_key,'tenant_name',t.display_name,'line_user_id',r.line_user_id,
  'display_name',r.display_name,'picture_url',r.picture_url,'requested_at',r.requested_at
 ) order by r.requested_at desc),'[]')
 into v_rows from public.lekhub_line_admin_requests r
 join public.lekhub_tenants t on t.tenant_key=r.tenant_key;
 return jsonb_build_object('ok',true,'rows',v_rows);
end $$;

create or replace function public.lekhub_owner_approve_admin_request(
 p_token text,p_tenant_key text,p_line_user_id text
) returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_req public.lekhub_line_admin_requests%rowtype;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true or
    coalesce(v_session->>'role','') not in ('owner','super_admin') then raise exception 'owner_required';end if;
 select * into v_req from public.lekhub_line_admin_requests
 where tenant_key=p_tenant_key and line_user_id=p_line_user_id;
 if not found then raise exception 'request_not_found';end if;
 insert into public.lekhub_line_admins(tenant_key,line_user_id,display_name,picture_url,role,is_active)
 values(v_req.tenant_key,v_req.line_user_id,v_req.display_name,v_req.picture_url,'admin',true)
 on conflict(tenant_key,line_user_id) do update set
  display_name=excluded.display_name,picture_url=excluded.picture_url,role='admin',is_active=true;
 delete from public.lekhub_line_admin_requests
 where tenant_key=p_tenant_key and line_user_id=p_line_user_id;
 return jsonb_build_object('ok',true,'tenant_key',p_tenant_key,'line_user_id',p_line_user_id);
end $$;

create or replace function public.lekhub_owner_update_tenant(
 p_token text,p_tenant_key text,p_patch jsonb
) returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v_session jsonb;v_row public.lekhub_tenants%rowtype;v_status text;v_extend int;v_expires timestamptz;v_ready boolean;
begin
 v_session:=public.lekhub_check_line_admin_session(p_token);
 if coalesce((v_session->>'ok')::boolean,false) is not true or
    coalesce(v_session->>'role','') not in ('owner','super_admin') then raise exception 'owner_required';end if;
 if p_tenant_key='platform' then raise exception 'platform_tenant_locked';end if;
 if p_patch?'status' then
  v_status:=p_patch->>'status';
  if v_status not in ('active','locked','expired') then raise exception 'invalid_status';end if;
 end if;
 if p_patch?'extendDays' then
  v_extend:=greatest(1,least(365,coalesce((p_patch->>'extendDays')::int,30)));
  select (case when expires_at is not null and expires_at>now() then expires_at else now() end)+make_interval(days=>v_extend)
  into v_expires from public.lekhub_tenants where tenant_key=p_tenant_key;
 end if;
 if p_patch?'isolationReady' then
  v_ready:=coalesce((p_patch->>'isolationReady')::boolean,false);
  if v_ready and not exists(
   select 1 from public.lekhub_tenant_secrets
   where tenant_key=p_tenant_key and nullif(trim(line_channel_access_token),'') is not null
  ) then raise exception 'tenant_line_token_required';end if;
 end if;
 update public.lekhub_tenants t set
  display_name=case when p_patch?'displayName' then coalesce(nullif(trim(p_patch->>'displayName'),''),t.display_name) else t.display_name end,
  line_channel_id=case when p_patch?'lineChannelId' then nullif(trim(p_patch->>'lineChannelId'),'') else t.line_channel_id end,
  line_liff_id=case when p_patch?'lineLiffId' then nullif(trim(p_patch->>'lineLiffId'),'') else t.line_liff_id end,
  expires_at=case when p_patch?'extendDays' then v_expires when p_patch?'expiresAt' then nullif(p_patch->>'expiresAt','')::timestamptz else t.expires_at end,
  status=case when p_patch?'status' then v_status when p_patch?'extendDays' or p_patch?'expiresAt' then 'active' else t.status end,
  locked_at=case when p_patch?'status' and v_status='locked' then now()
                 when p_patch?'status' and v_status<>'locked' then null
                 when p_patch?'extendDays' or p_patch?'expiresAt' then null else t.locked_at end,
  isolation_ready=case when p_patch?'isolationReady' then v_ready else t.isolation_ready end,
  isolation_ready_at=case when p_patch?'isolationReady' and v_ready then now()
                          when p_patch?'isolationReady' and not v_ready then null else t.isolation_ready_at end,
  updated_at=now()
 where t.tenant_key=p_tenant_key returning * into v_row;
 if not found then raise exception 'tenant_not_found';end if;
 return jsonb_build_object('ok',true,'row',to_jsonb(v_row));
end $$;

create or replace function public.lekhub_purge_expired_history(p_at timestamptz default now())
returns jsonb language plpgsql security definer set search_path='public'
as $$
declare v record;v_cutoff date;v_deleted int:=0;v_n int;
begin
 for v in
  select t.tenant_key,s.timezone,s.history_retention_days
  from public.lekhub_tenants t join public.lekhub_settings s on s.tenant_key=t.tenant_key
  where t.tenant_key<>'platform'
 loop
  v_cutoff:=((p_at at time zone v.timezone)::date-v.history_retention_days);
  delete from public.lekhub_activity_rewards where tenant_key=v.tenant_key and round_date<v_cutoff;
  delete from public.lekhub_backoffice_reports where tenant_key=v.tenant_key and round_date<v_cutoff;
  delete from public.lekhub_submissions where tenant_key=v.tenant_key and round_date<v_cutoff;
  get diagnostics v_n=row_count;v_deleted:=v_deleted+v_n;
 end loop;
 return jsonb_build_object('success',true,'deleted_submissions',v_deleted);
end $$;

commit;
